config/routes.rb
First_Website::Application.routes.draw do
devise_for :users
 
resources :decks
resources :cards
resource :search, :controller => :search do

  get :autocomplete_course_name, :on => :collection
  get :autocomplete_subject_name, :on => :collection
  get :autocomplete_school_name, :on => :collection

end
 
root to: 'static_pages#home'

delete 'decks' => 'decks#destroy', :as => :destroy_decks
delete 'cards' => 'cards#destroy', :as => :destroy_cards
get   'unsavedeck', to: 'decks#removefavorite'
get   'savedeck', to: 'decks#addfavorite'
get   'rate', to: 'decks#rate'
post   'rate', to: 'decks#rate'
get   'unrate', to: 'decks#unrate'
post   'unrate', to: 'decks#unrate'
get   'flag', to: 'decks#flag'

  match '/created_by', to: 'decks#thier_decks', via: 'get'
  match '/your_decks', to: 'decks#your_decks', via: 'get'
  match '/recent_decks', to: 'decks#recent', via: 'get'
  match '/saved_decks', to: 'decks#favorite', via: 'get'
  match '/results', to: 'search#search', via: 'get'
  match '/sort', to: 'search#sort', via: 'post'

  

end

app/models/deck.rb
class Deck < ActiveRecord::Base

		belongs_to :user
        belongs_to :saved_deck
        
        has_many  :cards, dependent: :destroy
        has_one  :course 
        has_one  :subject
        has_one  :school
        has_many :deckratings, dependent: :destroy
        has_many :flagged_decks, dependent: :destroy
 	
    validates :deck_title, :subject_name, presence: true
    validates_length_of :deck_title, :maximum => 50
    validates_length_of :subject_name, :maximum => 40
    validates_length_of :course_name, :maximum => 70
    validates_length_of :course_num, :maximum => 5

 	after_create :do_setID


  def self.search(subject, name, number, school, prof)
    query_obj = Deck.all
    query_obj = query_obj.where('subject_name like ?', "%#{subject}%") unless subject.blank?
    query_obj = query_obj.where('course_name like ?', "%#{name}%") unless name.blank?
    query_obj = query_obj.where('course_num like ?', "%#{number}%") unless number.blank?
    query_obj = query_obj.where('school_name like ?', "%#{school}%") unless school.blank?
    query_obj = query_obj.where('prof_name like ?', "%#{prof}%") unless prof.blank?
    query_obj
  end

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:deck_id => newID)


    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index

    @deck = Deck.new
    @decks = Deck.where(user_id: current_user.user_id).paginate(page: params[:page])
    @cards = Card.where(deck_id: @deck.deck_id).paginate(page: params[:page])
    if user_signed_in?
      @userID = current_user.user_id
      @user = current_user
      @school_name = @user.school_name
    end

  end
  def thier_decks
    @deck = Deck.new
    @user = User.find_by(:username => params[:username])
    @decks = Deck.where(user_id: @user.user_id).paginate(page: params[:page])
    if user_signed_in?
      @userID = current_user.user_id
      @school_name = @user.school_name
    end
    @cards = Card.where(deck_id: @deck.deck_id).paginate(page: params[:page])

  end
  def show
    if params[:count].nil?
    else
      @count= params[:count].to_i
    end
      @rating = Deckrating.new
      @deck =  Deck.find(params[:id])
    
      @cards = Card.where(deck_id: @deck.deck_id)
      if user_signed_in?
        @userID = current_user.user_id
        @recents = RecentDeck.where(user_id: current_user.user_id)
        #code to add deck to recent deck
        @check = RecentDeck.find_by(user_id: current_user.user_id,
              deck_id: @deck.deck_id)

        if  @check.nil?
          if  RecentDeck.count('deck_id', :distinct => true) <= 4            
          @recent = RecentDeck.create(user_id: current_user.user_id, 
          deck_id: @deck.deck_id, last_used: DateTime.now, card_id: 0)
          @recent.save
        else
          @earliest = RecentDeck.order(last_used: :asc).first
          @earliest.destroy
          @recent = RecentDeck.create(user_id: current_user.user_id, 
            deck_id: @deck.deck_id, last_used: DateTime.now, card_id: 0)
          @recent.save
          end
        else
          @check.last_used = DateTime.now
          @check.save
        end
      end
      
      #increment uses
      @deck.uses=@deck.uses+1
      @deck.save
  end
  def your_decks

    @deck = Deck.new
    @decks = Deck.where(user_id: current_user.user_id).paginate(page: params[:page])
    @cards = Card.where(deck_id: @deck.deck_id).paginate(page: params[:page])
    @user = current_user
    @userID = @user.user_id

    if user_signed_in?
      if current_user.sign_in_count == 1
        if session[:display_welcome].nil?
          flash.now[:notice] = "Welcome, " + current_user.username + "!"
          session[:display_welcome] = true
        end
      else 
        if session[:display_welcome].nil?
          flash.now[:notice] = "Welcome back, " + current_user.username + "!"
          session[:display_welcome] = true
        end
      end 
    end
           

  end
  def recent
    @recent = RecentDeck.new
    @recents = RecentDeck.where(user_id: current_user.user_id).order(last_used: :desc).order(last_used: :desc).paginate(page: params[:page])
    @deck = Deck.new
  end

  def unrate

    @oldrating = Deckrating.find_by(deck_id: params[:deckID], user_id: params[:userID])
    if !@oldrating.nil?
      @oldrating.destroy
      flash[:success] = "Rating removed"
    end
    redirect_to deck_path(params[:deckID], :count => params[:count])

  end

  def rate
    @rating = Deckrating.new

    if !Deckrating.find_by(deck_id: params[:deckID], user_id: params[:userID]).nil?
      @oldrating = Deckrating.find_by(deck_id: params[:deckID], user_id: params[:userID])
      @oldrating.destroy
    end

    @rating.deck_id= params[:deckID]
    @rating.user_id = params[:userID]
    @rating.deckrating_id = 0
    @rating.liked = params[:liked]
    @rating.created_at = DateTime.now
     
    if @rating.save
      if @rating.liked == true
        flash[:success] = 'Deck liked'
      else
        flash[:error] = 'Deck disliked'
      end
      redirect_to deck_path(@rating.deck_id, :count => params[:count])
    else
      redirect_to deck_path(@rating.deck_id, :count => params[:count])
    end

  end



  def favorite

  @favorite = SavedDeck.new
  @favorites = SavedDeck.where(user_id: current_user.user_id).paginate(page: params[:page])
  @userID = current_user.user_id

  end
  def addfavorite
    @deck = Deck.find(params[:favid])
    @user = User.find(params[:userID])
    @count = params[:count].to_i
    if !SavedDeck.find_by(user_id: @user.user_id, deck_id: @deck.deck_id).nil?
      redirect_to deck_path(@deck.deck_id, :count => @count)
    else  
      @favorite = SavedDeck.create(user_id: @user.user_id, deck_id: @deck.deck_id, 
                                      card_id:0, fav_id:0)
      @favorite.save
      redirect_to '/saved_decks'
    end
  end

  def removefavorite
    @deck = Deck.find(params[:favid])
    @userID = current_user.user_id
    if params[:count].nil?
      @favorite = SavedDeck.find_by(user_id: @userID, deck_id: @deck.deck_id)
      if @favorite.nil?
      else
        @favorite.destroy
        flash[:success] = "Deck un-saved."
      end
      redirect_to '/saved_decks'
    else
      @count = params[:count].to_i
      @favorite = SavedDeck.find_by(user_id: @userID, deck_id: @deck.deck_id)
      if @favorite.nil?
      else
        @favorite.destroy
        flash[:success] = "Deck un-saved."
      end
      redirect_to deck_path(@deck.deck_id, :count => @count)
    end
  end

  def edit
    @deck = Deck.find(params[:id])  
  end

  def update
    @deck = Deck.find(params[:id])
    if @deck.update_attributes(deck_params)

      if !@deck.course_name.blank? #set up course info
          @check = Course.find_by(name: @deck.course_name)
          if @check.nil?    #create a new course
            @newCourse = Course.create(subject_id: 0, 
                        course_id:0, course_num: @deck.course_num, name: @deck.course_name)
            @newCourse.save

            @deck.course_id = @newCourse.course_id
          else #match the course id
            @deck.course_id = @check.course_id
          end
        end

        if !@deck.subject_name.blank? #set up subject info
          @check = Subject.find_by(name: @deck.subject_name)
          if @check.nil? #create a new subject
            @newSubject = Subject.create(subject_id: 0, name: @deck.subject_name)
            @newSubject.save

            @deck.subject_id = @newSubject.subject_id
          else  #match the subject id
            @deck.subject_id = @check.subject_id
          end

        end

        if !@deck.school_name.blank? #set up school info
          @check = School.find_by(name: @deck.school_name)
          if @check.nil? #create a new school
            @newSchool = School.create(school_id: 0, name: @deck.school_name)
            @newSchool.save
          else 
            @deck.school_id = @check.school_id
          end
        else
          @deck.school_name = "~N/A~"
        end
      @deck.save

          
      flash[:success] = "Changes saved"
      redirect_to '/your_decks'         
    
    else
      flash[:error] = "Changes not saved. Try again."
      redirect_to new_card_path(:deck =>@card.deck_id)                       
    end
  end


  def create
  	if user_signed_in?
      @deck = Deck.new(deck_params)
      if @deck.save

        @deck.user_id = current_user.user_id

        
        if !@deck.course_name.blank? #set up course info
          @check = Course.find_by(name: @deck.course_name)
          if @check.nil?    #create a new course
            @newCourse = Course.create(subject_id: 0, 
                        course_id:0, course_num: @deck.course_num, name: @deck.course_name)
            @newCourse.save

            @deck.course_id = @newCourse.course_id
          else #match the course id
            @deck.course_id = @check.course_id
          end
        end

        if !@deck.subject_name.blank? #set up subject info
          @check = Subject.find_by(name: @deck.subject_name)
          if @check.nil? #create a new subject
            @newSubject = Subject.create(subject_id: 0, name: @deck.subject_name)
            @newSubject.save

            @deck.subject_id = @newSubject.subject_id
          else  #match the subject id
            @deck.subject_id = @check.subject_id
          end

        end

        if !@deck.school_name.blank? #set up school info
          @check = School.find_by(name: @deck.school_name)
          if @check.nil? #create a new school
            @newSchool = School.create(school_id: 0, name: @deck.school_name)
            @newSchool.save
          else 
            @deck.school_id = @check.school_id
          end
        else
          @deck.school_name = "~N/A~"
        end


        @deck.created_on = DateTime.now
        @deck.save
        @user = current_user
        @user.decks_made +=1
        @user.save

        flash[:success] = "Deck created!"
        redirect_to '/your_decks'
      else
          flash[:error] = "Please fill in all required fields."
          redirect_to '/decks'
      end
    
    end
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.user_id = -1
    @deck.save
    flash[:success] = "Deck deleted."
    redirect_to '/your_decks'
  end

  def flag

    if FlaggedDeck.find_by(:user_id => params[:userID], :deck_id => params[:deckID], :card_id => params[:cardID]).nil?
    @flag = FlaggedDeck.create(:user_id => params[:userID], :deck_id => params[:deckID], :card_id => params[:cardID])
    end

    flash[:success] = "Deck flagged. Thank you."
    redirect_to deck_path(params[:deckID], :count => params[:count])

  end



   private
    
    def deck_params
        params.require(:deck).permit(:deck_title, :course_num, :course_name, :subject_name, :school_name, :prof_name, :background)
    end

  
end

app/views/decks/edit.html.erb
<head>
  <script language="javascript" type="text/javascript">
    function CheckMaxlength(x)
    {
          var max = parseInt(x.getAttribute('maxlength'));
          var cur = x.value.length;

          if ( x.getAttribute && cur > max )
          {
              x.value = x.value.substring(0, max);
          }
    } 
</script>
</head>
<body>
       <%= render partial: 'shared/title'%>
        <br/><br/><br/>

 <%= simple_form_for @deck, :html => { :method => :put} do |f| %>

  <table>
    <tr>
      <td style= "vertical-align:top;">
        <div>
        <p> Fields marked with * are required </p>
        <div  class = "search">
          <div class = "hover">
            <p>* Title</p> 
            <%= f.text_field :deck_title, :onkeyup => "CheckMaxlength(this);", :maxlength => 50, :default => @deck.deck_title%>
            <div class = "tooltip" style = "top:65px;">
              50 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <div class = "hover">
          <p>* Subject</p>
          <%= f.autocomplete_field :subject_name, autocomplete_subject_name_search_path, :default => @deck.subject_name, :onkeyup => "CheckMaxlength(this);", :maxlength => 40  %>
          <div class = "tooltip" style = "top:65px;">
              40 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
           <p> School Name </p>
          <%= f.autocomplete_field :school_name, autocomplete_school_name_search_path, :default => @deck.school_name  %>
        </div>
        
        <div  class = "search">
          <div class = "hover">
          <p>Course Number</p>
          <%= f.text_field :course_num, :onkeyup => "CheckMaxlength(this);", :default => @deck.course_num, :maxlength => 5  %>
          <div class = "tooltip" style = "top:65px;">
              5 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <div class = "hover">
            <p>Course Name</p>
            <%= f.autocomplete_field :course_name, autocomplete_course_name_search_path, :default => @deck.course_name, :onkeyup => "CheckMaxlength(this);", :maxlength => 70 %>
            <div class = "tooltip" style = "top:65px;">
              70 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <p> Instructor (Last name, first name) </p>
          <%= f.text_field :prof_name, :default => @deck.prof_name %>
        </div>
       
        <p style= "font-size:10px;">Note: If either school, subject, and/or course name not found, a new entry will be created </p>

       <%= f.submit "Save Changes", class: "btn btn-medium btn-success" %>
       </div>

      </td>
      <td style = "padding-left:2em; vertical-align:top;">
      <%= f.label "Background image" %>
      <table>
        <tr>
          <td>
            
            <label for="deck_background_1">
            <%= image_tag('/assets/card1-6eb99ac61b498dd5de8d6a2ac9e359cc.jpg')  %>
            <%= f.radio_button :background, 1, :default => @deck.background  %>
            </label>
          </td>
          <td>
            <label for="deck_background_2">
            <%= image_tag('/assets/card2-44898f1306913eed194696f4ba5d825d.png')  %>
            <%= f.radio_button :background, 2 %>
            </label>
          </td>
          <td>
            <label for="deck_background_3">
            <%= image_tag('/assets/card3-91370e66d7bf6782e80bbfc0bcb6b185.png')  %>
            <%= f.radio_button :background, 3  %>
            </label>
          </td>
        </tr>
        <tr>
          <td>
            <label for="deck_background_4">
            <%= image_tag('/assets/card4-05a6a951b1d7dfa800801585a159e7d8.png')  %>
            <%= f.radio_button :background, 4  %>
            </label>
          </td>
          <td>
            <label for="deck_background_5">
            <%= image_tag('/assets/card5-aa8c004f6d145eb03020ae296543917d.png')  %>
            <%= f.radio_button :background, 5 %>
            </label>
          </td>
        </tr>
      </table>
      </td>
    </tr>
  </table>

<% end %>

</body>

app/views/decks/favorite.html.erb
<h1>Saved Decks</h1>

<% if user_signed_in? %>
  			<br/>
	<% if @favorites.any? %>
		  <div>
		  	<% @count = 0
		  	%><%@favorites1 = Deck.where(id: 0)
		  	%><%@favorites2 = Deck.where(id: 0)
		  	%><%@favorites.each do |d|
			  	%><%if(@count % 2 == 0)
			  	 	%><%@favorites1.push(d)
			  	%><%elsif(@count % 2 == 1)
			  	   	%><%@favorites2.push(d)
			  	%>
			  	<% end %>
			  	<% @count += 1 %>
			<% end %>
		  	<div class = "row" style= "align: center">
		  		<div class = "col-md-6" >
					<%= render partial: 'shared/favorite', collection: @favorites1 %>
				</div>
				<div class = "col-md-6" >
					<%= render partial: 'shared/favorite', collection: @favorites2 %>
				</div>
		  	</div>
		  <%= will_paginate @favorites %>
	<% end %>
<% end %>

app/views/decks/index.html.erb
<head>
  <script language="javascript" type="text/javascript">
    function CheckMaxlength(x)
    {
          var max = parseInt(x.getAttribute('maxlength'));
          var cur = x.value.length;

          if ( x.getAttribute && cur > max )
          {
              x.value = x.value.substring(0, max);
          }
    } 
</script>
</head>
<body>
<h1> Create a Deck</h1>

<%= simple_form_for @deck, :url => { :action => "create" } do |f| %>

  <table>
    <tr>
      <td style= "vertical-align:top;">
        <div>
        <p> Fields marked with * are required </p>
        <div  class = "search">
          <div class = "hover">
            <p>* Title</p> 
            <%= f.text_field :deck_title, :onkeyup => "CheckMaxlength(this);", :maxlength => 50, :default => @deck.deck_title%>
            <div class = "tooltip" style = "top:65px;">
              50 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <div class = "hover">
          <p>* Subject</p>
          <%= f.autocomplete_field :subject_name, autocomplete_subject_name_search_path, :default => @deck.subject_name, :onkeyup => "CheckMaxlength(this);", :maxlength => 40  %>
          <div class = "tooltip" style = "top:65px;">
              40 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <p> School Name </p>
          <%= f.autocomplete_field :school_name, autocomplete_school_name_search_path, :value => @user.school_name  %>
        </div>
        
        <div  class = "search">
          <div class = "hover">
          <p>Course Number</p>
          <%= f.text_field :course_num, :onkeyup => "CheckMaxlength(this);", :default => @deck.course_num, :maxlength => 5  %>
          <div class = "tooltip" style = "top:65px;">
              5 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <div class = "hover">
            <p>Course Name</p>
            <%= f.autocomplete_field :course_name, autocomplete_course_name_search_path, :default => @deck.course_name, :onkeyup => "CheckMaxlength(this);", :maxlength => 70 %>
            <div class = "tooltip" style = "top:65px;">
              70 character limit
            </div>
          </div>
        </div>

        <div  class = "search">
          <p>Instructor (Last name, first name) </p>
          <%= f.text_field :prof_name, :default => @deck.prof_name %>
        </div>
       
        <p style= "font-size:10px;">Note: If either school, subject, and/or course name not found, a new entry will be created </p>

       <%= f.submit "Create Deck", class: "btn btn-medium btn-success" %>
       </div>

      </td>
      <td style = "padding-left:2em; vertical-align:top;">
      <%= f.label "Background image" %>
      <table>
        <tr>
          <td>
            
            <label for="deck_background_1">
            <%= image_tag('/assets/card1-6eb99ac61b498dd5de8d6a2ac9e359cc.jpg')  %>
            <%= f.radio_button :background, 1, :default => @deck.background  %>
            </label>
          </td>
          <td>
            <label for="deck_background_2">
            <%= image_tag('/assets/card2-44898f1306913eed194696f4ba5d825d.png')  %>
            <%= f.radio_button :background, 2 %>
            </label>
          </td>
          <td>
            <label for="deck_background_3">
            <%= image_tag('/assets/card3-91370e66d7bf6782e80bbfc0bcb6b185.png')  %>
            <%= f.radio_button :background, 3  %>
            </label>
          </td>
        </tr>
        <tr>
          <td>
            <label for="deck_background_4">
            <%= image_tag('/assets/card4-05a6a951b1d7dfa800801585a159e7d8.png')  %>
            <%= f.radio_button :background, 4  %>
            </label>
          </td>
          <td>
            <label for="deck_background_5">
            <%= image_tag('/assets/card5-aa8c004f6d145eb03020ae296543917d.png')  %>
            <%= f.radio_button :background, 5 %>
            </label>
          </td>
        </tr>
      </table>
      </td>
    </tr>
  </table>

<% end %>


</body>

app/views/decks/recent.html.erb
<h1>Recent Decks</h1>

<% if user_signed_in? %>
  			<br/>
  			<br/>
	
	<% if @recents.any? %>
		  <div>
		  	<% @count = 0
		  	%><%@recents1 = Deck.where(id: 0)
		  	%><%@recents2 = Deck.where(id: 0)
		  	%><%@recents.each do |d|
			  	%><%if(@count % 2 == 0)
			  	 	%><%@recents1.push(d)
			  	%><%elsif(@count % 2 == 1)
			  	   	%><%@recents2.push(d)
			  	%>
			  	<% end %>
			  	<% @count += 1 %>
			<% end %>
		  	<div class = "row" style= "align: center">
		  		<div class = "col-md-6" >
					<%= render partial: 'shared/recent', collection: @recents1 %>
				</div>
				<div class = "col-md-6" >
					<%= render partial: 'shared/recent', collection: @recents2 %>
				</div>
		  	</div>
		  <%= will_paginate @recents %>
	<% end %>
<% end %>

app/views/decks/thier_decks.html.erb
<h1>Decks created by <%= @user.username %></h1>
<% if @decks.any? %>
		  <div>
		  	<% @count = 0
		  	%><%@deck1 = Deck.where(id: 0)
		  	%><%@deck2 = Deck.where(id: 0)
		  	%><%@deck3 = Deck.where(id: 0)
		  	%><%@deck4 = Deck.where(id: 0)
		  	%><%@decks.each do |d|
			  	%><%if(@count % 4 == 0)
			  	 	%><%@deck1.push(d)
			  	%><%elsif(@count % 4 == 1)
			  	   	%><%@deck2.push(d)
			  	%><%elsif(@count % 4 == 2)
			  	   	%><%@deck3.push(d)
			  	%><%else
			  	  	%><%@deck4.push(d)
			  	%>
			  	<% end %>
			  	<% @count += 1 %>
			<% end %>
		  	<div class = "row" style= "align: center">
		  		<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck1 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck2 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck3 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck4 %>
				</div>
			</div>
		  </div>
		  <%= will_paginate @decks %>
	<% end %>

app/views/decks/your_decks.html.erb
<h1>Your Decks</h1>

<% if user_signed_in? %>
    	<div class="row", style = "border-bottom: 3px solid black">
  			<%= link_to'Create a Deck', '/decks', class: "btn btn-medium btn-success"  %>  
  			<br/>
  			<br/>
   		</div>
	
	<% if @decks.any? %>
		  <div>
		  	<% @count = 0
		  	%><%@deck1 = Deck.where(id: 0)
		  	%><%@deck2 = Deck.where(id: 0)
		  	%><%@deck3 = Deck.where(id: 0)
		  	%><%@deck4 = Deck.where(id: 0)
		  	%><%@decks.each do |d|
			  	%><%if(@count % 4 == 0)
			  	 	%><%@deck1.push(d)
			  	%><%elsif(@count % 4 == 1)
			  	   	%><%@deck2.push(d)
			  	%><%elsif(@count % 4 == 2)
			  	   	%><%@deck3.push(d)
			  	%><%else
			  	  	%><%@deck4.push(d)
			  	%>
			  	<% end %>
			  	<% @count += 1 %>
			<% end %>
		  	<div class = "row" style= "align: center">
		  		<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck1 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck2 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck3 %>
				</div>
				<div class = "col-sm-3" >
					<%= render partial: 'shared/decks', collection: @deck4 %>
				</div>
			</div>
		  </div>
		  <%= will_paginate @decks %>
	<% end %>
<% end %>