config/routes.rb
First_Website::Application.routes.draw do
devise_for :users
 
resources :decks
resources :cards
resource :search, :controller => :search do

  get :autocomplete_course_name, :on => :collection
  get :autocomplete_subject_name, :on => :collection
  get :autocomplete_school_name, :on => :collection

end
 
root to: 'static_pages#home'

delete 'decks' => 'decks#destroy', :as => :destroy_decks
delete 'cards' => 'cards#destroy', :as => :destroy_cards
get   'unsavedeck', to: 'decks#removefavorite'
get   'savedeck', to: 'decks#addfavorite'
get   'rate', to: 'decks#rate'
post   'rate', to: 'decks#rate'
get   'unrate', to: 'decks#unrate'
post   'unrate', to: 'decks#unrate'
get   'flag', to: 'decks#flag'

  match '/created_by', to: 'decks#thier_decks', via: 'get'
  match '/your_decks', to: 'decks#your_decks', via: 'get'
  match '/recent_decks', to: 'decks#recent', via: 'get'
  match '/saved_decks', to: 'decks#favorite', via: 'get'
  match '/results', to: 'search#search', via: 'get'
  match '/sort', to: 'search#sort', via: 'post'

  

end

app/models/card.rb
class Card < ActiveRecord::Base

	

		belongs_to :deck
		belongs_to :recent_deck
		belongs_to :saved_deck
		
		

		has_one  :deck
		validates :atext, :qtext, presence: true
		validates_length_of :atext, :qtext, :maximum => 255
 
        
 	after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:card_id => newID)
	end
end

app/models/course.rb
class Course < ActiveRecord::Base

	belongs_to :subject

    after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:course_id => newID)


    end
 
end

app/models/deck.rb
class Deck < ActiveRecord::Base

		belongs_to :user
        belongs_to :saved_deck
        
        has_many  :cards, dependent: :destroy
        has_one  :course 
        has_one  :subject
        has_one  :school
        has_many :deckratings, dependent: :destroy
        has_many :flagged_decks, dependent: :destroy
 	
    validates :deck_title, :subject_name, presence: true
    validates_length_of :deck_title, :maximum => 50
    validates_length_of :subject_name, :maximum => 40
    validates_length_of :course_name, :maximum => 70
    validates_length_of :course_num, :maximum => 5

 	after_create :do_setID


  def self.search(subject, name, number, school, prof)
    query_obj = Deck.all
    query_obj = query_obj.where('subject_name like ?', "%#{subject}%") unless subject.blank?
    query_obj = query_obj.where('course_name like ?', "%#{name}%") unless name.blank?
    query_obj = query_obj.where('course_num like ?', "%#{number}%") unless number.blank?
    query_obj = query_obj.where('school_name like ?', "%#{school}%") unless school.blank?
    query_obj = query_obj.where('prof_name like ?', "%#{prof}%") unless prof.blank?
    query_obj
  end

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:deck_id => newID)


    end
end

app/models/deckrating.rb
class Deckrating < ActiveRecord::Base

        belongs_to :deck

        after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:deckrating_id => newID)


    end
        
 
end

app/models/flagged_deck.rb
class FlaggedDeck < ActiveRecord::Base

	belongs_to :deck
 	
end

app/models/recent_deck.rb
class RecentDeck < ActiveRecord::Base

        belongs_to :user
        belongs_to :deck

       has_one :card

 
end

app/models/result.rb
class Result < ActiveRecord::Base

end

app/models/saved_card.rb
class SavedCard < ActiveRecord::Base

        has_one :card
        belongs_to :user
        
        after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:fav_id => newID)


    end
 
end

app/models/saved_deck.rb
class SavedDeck < ActiveRecord::Base

        belongs_to :user
        has_one :deck

        has_one :card
        after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:fav_id => newID)


    end

 
end

app/models/school.rb
class School < ActiveRecord::Base
		
        has_many  :courses
        has_many  :decks
 		after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:school_id => newID)


    end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
		
        has_many  :courses, dependent: :destroy
        has_many  :decks, dependent: :destroy
 		after_create :do_setID

  private
    def do_setID
      
      newID = self.id
      self.update_attributes(:subject_id => newID)


    end
end

app/models/user.rb
class User < ActiveRecord::Base

        has_many  :decks, dependent: :destroy
        has_many  :deckratings, dependent: :destroy
        has_many  :recent_decks, dependent: :destroy
        has_many  :saved_decks, dependent: :destroy
        has_many :flagged_decks, dependent: :destroy



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
  validates :username, uniqueness: true

  validates :username, :decks_made,  presence:  true
  validates_inclusion_of  :admin, :in => [true, false]
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }

  after_create :do_setID
  
  private

    def do_setID
      
      newID = self.id
      self.update_attributes(:user_id => newID)


    end

    def self.find_for_database_authentication(conditions={})
      self.where("username = ?", conditions[:email]).limit(1).first ||
      self.where("email = ?", conditions[:email]).limit(1).first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "SCFlashcards"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/minimal_form_helper.rb
require "minimal_form_builder"
module MinimalFormHelper
  def minimal_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end

  def minimal_fields_for(*args, &block)
    options = args.extract_options!
    simple_fields_for(*(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in_(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
   def signed_in?
    !current_user.nil?
  end
   def current_user=(user)
    @current_user = user
  end

   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end



   


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper

   def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="social-icons">
<p>
      
    </p>

</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SC Flashcards", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            
            <li><%= link_to "Search", search_path, id: "brand" %></li>   
            <li><%= link_to "Your Decks", '/your_decks', id: "brand" %></li>   
            <li><%= link_to "Recent Decks", '/recent_decks', id: "brand" %></li>   
            <li><%= link_to "Saved Decks", saved_decks_path, id: "brand" %></li> 
            <li><%= link_to "Account", edit_user_registration_path, id: "brand" %></li> 
            <li><%= link_to'Sign Out', destroy_user_session_path, :method => :delete, id:"brand" %>  </li>     
          <% else %>
            <li><%= link_to "Search", search_path, id: "brand" %></li> 
            <li><%= link_to "Sign In", new_user_session_path, id: "brand" %></li> 
            <li><%= link_to "Sign Up", new_user_registration_path, id: "brand" %></li>
            
          <% end %>
          

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_responsiveheader.html.erb
<nav class="navbar navbar-default" role="navigation" >
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header" style = "background-color:black;">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style = "background-color:black;">
    <ul class="nav pull-left">
        <li><%= link_to "SC Flashcards", root_path, id: "logo",  style:"text-shadow:none;padding-left:120px;" %></li>
    </ul>
    <ul class="nav pull-right">
      <% if user_signed_in? %>
            
        <li><%= link_to "Search", search_path, id: "brand", style:"text-shadow:none;" %></li>   
        <li><%= link_to "Your Decks", '/your_decks', id: "brand", style:"text-shadow:none;" %></li>   
        <li><%= link_to "Recent Decks", '/recent_decks', id: "brand", style:"text-shadow:none;" %></li>   
        <li><%= link_to "Saved Decks", saved_decks_path, id: "brand", style:"text-shadow:none;" %></li> 
        <li><%= link_to "Account", edit_user_registration_path, id: "brand", style:"text-shadow:none;" %></li> 
        <li><%= link_to'Sign Out', destroy_user_session_path, :method => :delete, id:"brand", style:"text-shadow:none;" %>  </li>     
      <% else %>
        <li><%= link_to "Search", search_path, id: "brand", style:"text-shadow:none;" %></li> 
        <li><%= link_to "Sign In", new_user_session_path, id: "brand", style:"text-shadow:none;" %></li> 
        <li><%= link_to "Sign Up", new_user_registration_path, id: "brand", style:"text-shadow:none;padding-right:120px;" %></li>
            
      <% end %>
          
    </ul>
   
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "autocomplete-rails.js" %>
    <%= csrf_meta_tags %>
    <link rel="icon" href="images/favicon.ico" type="image/ico" />
  </head>
  <body>
    <%= render 'layouts/responsiveheader' %>
    
    <div class="container-fluid" style = "padding-left:6em;padding-right:6em;">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div>
     </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>


  </body>
</html>

app/views/shared/_cards.html.erb
<head>
</head>
  <body>
    
    <table>
      <tr>
        <td style = "width:26em; vertical-align: top;"><p class = "cardBody"><%= cards.qtext %></p></td>
        <td style = "width:26em; vertical-align: top;"><p class = "cardBody"><%= cards.atext %></p></td>
        <% if !cards.nil? %>
          <% if Deck.find_by(deck_id: cards.deck_id).user_id == @userID %>
            <td><%= link_to "Edit this Card", edit_card_path(cards.card_id), class: "btn btn-small btn-info"%></td>
            <td><%= link_to "Delete this Card", cards, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %></td>
            <% end %>
          <% end %>
      </tr>
    </table>
 </body>


        
   
    
   
   

app/views/shared/_decks.html.erb
<head>
  <style>
  #container {
    border-radius: 5px;
    background-color: white;
    border: 1px solid #000;
    overflow: hidden;
    }

  #container > div {
    height: 200px;
    background-color: red;
}
  </style>
</head>
<body>
<div>
  <table> 
    <tr>
      <td style = "width:158px">
        <a href = "/decks/<%= decks.deck_id %>" style = "color:black;"><table class = "deck<%= decks.background%>">
          <tr style = "text-align: center; height:4em;">
            <td>
                <p class ="cardTitle2">
                  <% if decks.deck_title.length <27 %>
                    <%= decks.deck_title %>
                  <% else %>
                    <%= decks.deck_title[0,27]%>...
                  <% end %>
                </p>
          </tr>
          <tr style = "text-align:center; vertical-align:top; padding-top: 5px;">
            <td>
              <p class="cardBody2"><%= decks.subject_name %>
              <% if !decks.course_num.blank? %>
                - <%= decks.course_num %>
               <% end %>
              <% if !decks.course_name.blank?  %> 
                <% if decks.course_name.length <27 %>
                    -<%= decks.course_name %>
                  <% else %>
                    -<%= decks.course_name[0,27]%>...
                  <% end %>
                <% end %>
              </p>
            </td>
          </tr>
            <tr>
              <td style = "width:8em; padding-left:60px;:right;vertical-align:bottom; padding-bottom:10px">
                <% if Deckrating.where(deck_id: decks.deck_id).empty? %>
                  <div class = 'likedText'> No ratings </div>
                <% else %>
                  <% @liked = Deckrating.where(deck_id: decks.deck_id, liked: true).count %>
                  <% @total = Deckrating.where(deck_id: decks.deck_id).count %>
                  <% @percent = (@liked * 100 / @total) %>
                  <% if @percent > 49 %>
                   <div class = 'likedText', style = "color:#0D55D1;text-align:right">
                      <%= @percent %>% liked <br>
                      <div id="container" style="width: 88px; height: 10px; position:relative;right:-2px">
                       <canvas id="myCanvas<%=decks.deck_id%>" width="90" height="20" style = "solid #FF0000"></canvas>  

                      <script type = "text/javaScript">
                          var pct = <%=@percent.to_json%>;
                          var c=document.getElementById("myCanvas<%=decks.deck_id%>");
                          var ctx=c.getContext("2d");
                                var grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "pink");
                                grad.addColorStop(0.5, "red");
                                grad.addColorStop(1.0, "red");

                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90, 30);

                                grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "white");
                                grad.addColorStop(0.5, "#0D55D1");
                                grad.addColorStop(1.0, "#0D55D1");
                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90*(pct/100), 30);
                          ctx.lineWidth="1";
                          ctx.rect(-5,-5, 90*(pct/100)+5, 30+5);
                          ctx.stroke();
                      </script>

                      </div>
                    </div>
                    </div>
                  <% else %>
                    <div class = 'likedText', style = "color:#FF0000;text-align:right">
                      <%= @percent %>% liked <br>
                       <div id="container" style="width: 88px; height: 10px; position:relative;right:-2px">
                      <canvas id="myCanvas<%=decks.deck_id%>" width="90" height="20" style = "solid #FF0000"></canvas>     

                          <script type = "text/javaScript">
                          var pct = <%=@percent.to_json%>;
                          var c=document.getElementById("myCanvas<%=decks.deck_id%>");
                          var ctx=c.getContext("2d");
                                var grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "pink");
                                grad.addColorStop(0.5, "red");
                                grad.addColorStop(1.0, "red");

                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90, 30);

                                grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "white");
                                grad.addColorStop(0.5, "#0D55D1");
                                grad.addColorStop(1.0, "#0D55D1");
                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90*(pct/100), 30);
                          ctx.lineWidth="1";
                          ctx.rect(-5,-5, 90*(pct/100)+5, 30+5);
                          ctx.stroke();
                      </script>

                      </div>
                    </div>                  <% end %>
                <% end %>
              </td>
            </tr>
        </table> </a>
      <td style = "vertical-align: top;">
        <table style = "vertical-align: top;">
          <tr>
            </tr>
            <% if !@user.nil? && @userID == decks.user_id %>
              <td style = "width:8em">
                <div class = "hover">
                <%= link_to image_tag('edit.png'), edit_deck_path(decks.deck_id), class: "btn btn-small btn-warning"%>
                <div class = "tooltip" style = "width:8em; top:25px">
              Deck properties
            </div>
          </div>
              </td>
              <% else %>
              <td style = "width:8em">
              </td>
            <% end %>
            </tr>
            <tr>
              <% if !@user.nil? && @userID == decks.user_id %>
              <td style = "width:8em">
                <div class = "hover">
                <%= link_to image_tag('add.png'), new_card_path(:deck => decks.deck_id), class: "btn btn-small btn-info" %>
                 <div class = "tooltip" style = "width:7em; top:25px">
              Add/edit cards
            </div>
          </div>
              </td>
              <% end %>
            </tr>
            <tr>
              <% if !@user.nil? && @userID == decks.user_id %>
              <td style = "width:8em">
                <div class = "hover">
               <%= link_to image_tag('delete.png', :title=>"Delete this deck"), decks, method: :delete, data: { confirm: "Are you sure you want to delete this deck?" }, class: "btn btn-small btn-danger" %>
               <div class = "tooltip" style = "width:7.5em; top:25px">
              Delete this deck
            </div>
          </div>
              </td>
              <% end %>
            </tr>
          </table>
        </td>
      </td>
    </tr>
   
  </table>
</div>
</br>
</body>
   
   

app/views/shared/_favorite.html.erb
<% @deck=Deck.find_by(deck_id: favorite.deck_id) %>
<head>
    <style>
  #container {
    border-radius: 5px;
    background-color: white;
    border: 1px solid #000;
    overflow: hidden;
    }

  #container > div {
    height: 200px;
    background-color: red;
}
  </style>
</head>
<body>
  <% if !@deck.nil? %>
<div class="row">
  <br>

   <table>
    <tr>
      <td>
       <table> 
        <tr>
          <td style = "width:158px">
             <a href = "/decks/<%= @deck.deck_id %>" style = "color:black;"><table class = "deck<%= @deck.background%>">
              <tr style = "text-align: center; height:4em;">
                <td>
                    <p class ="cardTitle2">
                      <% if @deck.deck_title.length <27 %>
                        <%= @deck.deck_title %>
                      <% else %>
                        <%= @deck.deck_title[0,27]%>...
                      <% end %>
                    </p>
                  </td>
              </tr>
              <tr style = "text-align:center; vertical-align:top; padding-top: 5px;">
                <td>
                  <p class="cardBody2"><%= @deck.subject_name %>
                  <% if !@deck.course_num.blank? %>
                    - <%= @deck.course_num %>
                   <% end %>
                  <% if !@deck.course_name.blank?  %> 
                    <% if @deck.course_name.length <27 %>
                        -<%= @deck.course_name %>
                      <% else %>
                        -<%= @deck.course_name[0,27]%>...
                      <% end %>
                    <% end %>
                  </p>
                </td>
              </tr>
               <tr>
                   <td style = "width:8em; padding-left:60px;:right;vertical-align:bottom; padding-bottom:10px">
                    <% if Deckrating.where(deck_id: @deck.deck_id).empty? %>
                      <div class = 'likedText'> No ratings </div>
                    <% else %>
                      <% @liked = Deckrating.where(deck_id: @deck.deck_id, liked: true).count %>
                      <% @total = Deckrating.where(deck_id: @deck.deck_id).count %>
                                           <% @percent = (@liked * 100 / @total) %>
                  <% if @percent > 49 %>
                   <div class = 'likedText', style = "color:#0D55D1;text-align:right">
                      <%= @percent %>% liked <br>
                      <div id="container" style="width: 88px; height: 10px; position:relative;right:-2px">
                       <canvas id="myCanvas<%=favorite.deck_id%>" width="90" height="20" style = "solid #FF0000"></canvas>  

                      <script type = "text/javaScript">
                          var pct = <%=@percent.to_json%>;
                          var c=document.getElementById("myCanvas<%=favorite.deck_id%>");
                          var ctx=c.getContext("2d");
                                var grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "pink");
                                grad.addColorStop(0.5, "red");
                                grad.addColorStop(1.0, "red");

                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90, 30);

                                grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "white");
                                grad.addColorStop(0.5, "#0D55D1");
                                grad.addColorStop(1.0, "#0D55D1");
                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90*(pct/100), 30);
                          ctx.lineWidth="1";
                          ctx.rect(-5,-5, 90*(pct/100)+5, 30+5);
                          ctx.stroke();
                      </script>

                      </div>
                    </div>
                    </div>
                  <% else %>
                    <div class = 'likedText', style = "color:#FF0000;text-align:right">
                      <%= @percent %>% liked <br>
                       <div id="container" style="width: 88px; height: 10px; position:relative;right:-2px">
                      <canvas id="myCanvas<%=favorite.deck_id%>" width="90" height="20" style = "solid #FF0000"></canvas>     

                          <script type = "text/javaScript">
                          var pct = <%=@percent.to_json%>;
                          var c=document.getElementById("myCanvas<%=favorite.deck_id%>");
                          var ctx=c.getContext("2d");
                                var grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "pink");
                                grad.addColorStop(0.5, "red");
                                grad.addColorStop(1.0, "red");

                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90, 30);

                                grad = ctx.createLinearGradient(0,0,0, 20);
                                grad.addColorStop(0, "white");
                                grad.addColorStop(0.5, "#0D55D1");
                                grad.addColorStop(1.0, "#0D55D1");
                          ctx.fillStyle=grad;
                          ctx.fillRect(0,0, 90*(pct/100), 30);
                          ctx.lineWidth="1";
                          ctx.rect(-5,-5, 90*(pct/100)+5, 30+5);
                          ctx.stroke();
                      </script>

                      </div>
                    </div>                  <% end %>
                <% end %>
                  </td>
                </tr>
            </table> </a>
          </td>
        </table>
      </td>
      <td>
        <table>
          <tr>
            <td>
            <table>
              <tr>
               <% if @deck.user_id != -1 %>
             <td class= "deckPartial" style = "width:150px;">
              
                <p class = 'cardTitle2' style = "vertical-align:top; text-align:left;"> 
                  Created by
                </p>
                  <p class = 'cardBody2' style = "vertical-align:top; text-align:left; margin-bottom: 0px">
                  <% if !@deck.nil? %>
                    <% @username = User.find_by(user_id: @deck.user_id).username %>
                    <%= link_to @username, {:controller => "decks", :action => "thier_decks", :username => @username } %>
                  <% end %>
                </p>
                
            </td>
            <% end %>
            <td class= "deckPartial" style ="width:150px">
              <p class = 'cardTitle2' style = "vertical-align:top; text-align:left;"> 
                Created on
              </p>
              <p class = 'cardBody2' style = "vertical-align:top; text-align:left; margin-bottom: 0px"> 
                <%= @deck.created_on.strftime("%b-%d-%Y") %> 
              </p>
            </td>
           </tr>
          </table>
        </td>
          </tr>
          <tr>
            <td class= "deckPartial" style="width:300px">
              <p class = 'cardTitle2' style = "vertical-align:top; text-align:left;"> 
                School
              </p>
                <p class = 'cardBody2' style = "vertical-align:top; text-align:left; max-width: 300px; margin-bottom: 0px"> 
                <%if @deck.school_name.nil? %> 
                Unspecified
                <%else%> 
                <%= @deck.school_name %>
                <%end%>
                </p> 
            </td>

          </tr>
          <tr>
            <td class= "deckPartial">
              <p class = 'cardTitle2' style = "vertical-align:top; text-align:left;"> 
                Instructor 
              </p>
              <p class = 'cardBody2' style = "vertical-align:top; text-align:left; margin-bottom: 0px">
                <%if @deck.prof_name.nil? %> 
                Unspecified
                <%else%> 
                <%= @deck.prof_name %>
                <%end%> 
              </p>
            </td>
          </tr>
          <tr>
    <td>
      <table style = "height:50px">
        <tr>
          <td style = "vertical-align:bottom;">
            <% if user_signed_in? %>
                <% if SavedDeck.find_by(:user_id => @userID, :deck_id => @deck.deck_id).nil? %>
                <div class= "hover">
                  <%= link_to image_tag('save.png'), {:controller => "decks", :action => 'addfavorite',:userID => @userID,:favid => @deck.deck_id}, class: "btn btn-small btn-success"%>
                  <div class = "tooltip">
                    Save this Deck
                  </div>
                </div>
                <% else %>
                <div class= "hover">
                  <%= link_to image_tag('unsave.png'), {:controller => "decks", :action => 'removefavorite', :userID => @userID,:favid => @deck.deck_id}, class: "btn btn-small btn-warning" %>
                  <div class = "tooltip">
                    Forget this Deck
                  </div>
                </div>
                <% end %>
              <% else %>
              <% end %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
      </table>
    </td>
  </tr>
</table>
</div>
<% end %>
</body>

app/views/shared/_show.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        var keys = [];
        var code = [65];
        var toShow = true;
        $(document).keydown(function(keyEvent) {
          keys.push(keyEvent.keyCode);
          if ( keys.length > code.length ) {
            keys.shift();
          }
          if(keys.toString() == code.toString()){
            $('#showAnswer').toggle(toShow);
            $('#hideAnswer').toggle(!toShow);
            $("#hideAButton").toggle(toShow);
            $("#showAButton").toggle(!toShow);
            toShow = !toShow;
          }
          //This is a comment in javascript
      
        });
      });
    </script>